apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: annotate-secret-job
rules:
  - resources:
      - secret
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: annotate-secret-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: annotate-secret-job
subjects:
  - kind: ServiceAccount
    name: annotate-secret-job
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: annotate-secret-job