apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: large
spec:
  labelSelector:
    matchLabels:
      size: large
  templates:
  - objectTemplate: |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: large
        namespace: {{ .Name }}
      spec:
        hard:
          requests.cpu: "8"
          requests.memory: "4Gi"