apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: small
spec:
  labelSelector:
    matchLabels:
      size: small
  templates:
  - objectTemplate: |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: small
        namespace: {{ .Name }}
      spec:
        hard:
          requests.cpu: "4"
          requests.memory: "2Gi"
          limits.memory: "4Gi"
  - objectTemplate: |
      apiVersion: "v1"
      kind: "LimitRange"
      metadata:
        name: "small"
      spec:
        limits:
          - type: "Container"
            default:
              memory: "1Gi"
            defaultRequest:
              cpu: "200m"
              memory: "128Mi"