apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: namespace-configuration-operator

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
- github.com/redhat-canada-gitops/catalog/namespace-configuration-operator/overlays/default?ref=master

resources:
- small-ns-config.yaml
- medium-ns-config.yaml
- large-ns-config.yaml
- multitenant.yaml