apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

bases:
- github.com/redhat-canada-gitops/catalog/sealed-secrets-operator/base

resources:
- role-anyuid.yaml

commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
  argocd.argoproj.io/sync-options: Prune=false