apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-authentication
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/oauth/overlays/default
    repoURL: https://github.com/gnunn-gitops/cluster-config.git
    targetRevision: unify
  syncPolicy:
    automated:
      prune: false
      selfHeal: false