apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../environments/overlays/default

# Having issues with app-of-app pattern, debug later
# resources:
# - cluster-config-manager-app.yaml